<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationIcon>Resources/tomato.ico</ApplicationIcon>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Tomato.WindowsGui</AssemblyName>
    <RootNamespace>Tomato.WindowsGui</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Tomato.WindowsCore/Tomato.WindowsCore.csproj" />
  </ItemGroup>
</Project>
